# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3ViDotoyAfYa4RqJRIjLGHWG6RBpvl6
"""

"""
Experiment 8 - Matched filtering, ISI and eye diagrams
BPSK over an RRC-shaped, AWGN channel with a matched-filter receiver.
No communications toolbox is used; every building block (RRC filter,
eye-diagram plotting, ISI channel, BER estimation) is implemented from
first principles with numpy / scipy only.

HOW TO RUN IN GOOGLE COLAB
---------------------------
1. Open https://colab.research.google.com -> New notebook.
2. Paste this entire file into a single code cell (numpy, scipy and
   matplotlib are pre-installed in Colab, so no pip install is needed).
3. Run the cell (Shift+Enter). Every required plot (transmit/matched-filter
   waveform, eye diagrams vs SNR, eye diagrams vs timing offset, eye height
   vs SNR, BER vs timing offset, the multipath-ISI eye comparison, and the
   simulated-vs-theoretical BER curve) will be displayed inline below the
   cell, and also saved as PNG files under a local "figs/" folder (visible
   in the Colab file browser on the left).
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import erfc

os.makedirs("figs", exist_ok=True)
rng = np.random.default_rng(7)

# ----------------------------------------------------------------------
# 1. Root-raised-cosine (RRC) pulse design
# ----------------------------------------------------------------------
def rrc_filter(beta, span, sps):
    """
    Root-raised-cosine filter impulse response.
    beta : roll-off factor (0 <= beta <= 1)
    span : filter length in symbol periods (total length = span*sps + 1)
    sps  : samples per symbol
    Returns (t, h) where t is time in symbol periods and h is normalised
    to unit energy.
    """
    N = span * sps
    t = (np.arange(-N / 2, N / 2 + 1)) / sps  # time in units of T (symbol period)
    h = np.zeros_like(t)

    for i, ti in enumerate(t):
        if np.isclose(ti, 0.0):
            h[i] = (1 / np.sqrt(1)) * (1 - beta + 4 * beta / np.pi)
        elif beta > 0 and np.isclose(abs(ti), 1 / (4 * beta)):
            h[i] = (beta / np.sqrt(2)) * (
                (1 + 2 / np.pi) * np.sin(np.pi / (4 * beta))
                + (1 - 2 / np.pi) * np.cos(np.pi / (4 * beta))
            )
        else:
            num = np.sin(np.pi * ti * (1 - beta)) + 4 * beta * ti * np.cos(
                np.pi * ti * (1 + beta)
            )
            den = np.pi * ti * (1 - (4 * beta * ti) ** 2)
            h[i] = num / den

    h = h / np.sqrt(np.sum(h ** 2))  # unit-energy normalisation
    return t, h


# ----------------------------------------------------------------------
# 2. BPSK source, pulse shaping, AWGN, matched filtering
# ----------------------------------------------------------------------
def bpsk_symbols(n_sym, rng):
    bits = rng.integers(0, 2, n_sym)
    return 2 * bits - 1, bits  # +/-1 symbols


def upsample(symbols, sps):
    x = np.zeros(len(symbols) * sps)
    x[::sps] = symbols
    return x


def add_awgn(x, snr_db, sps):
    """AWGN sized for the given Es/N0 (SNR per symbol) at sps samples/symbol."""
    snr_lin = 10 ** (snr_db / 10)
    sig_power = np.mean(np.abs(x) ** 2) * sps  # power referred to symbol rate
    noise_power = sig_power / snr_lin
    noise = np.sqrt(noise_power / 2) * rng.standard_normal(len(x))
    return x + noise


def matched_filter_chain(n_sym=4000, sps=8, span=6, beta=0.35, snr_db=10,
                          channel_taps=None, rng=rng):
    """
    Full tx -> channel -> rx chain.
    channel_taps: optional multipath ISI channel, e.g. [1, 0.5] (in symbol-spaced taps,
                  applied at the sample rate by upsampling the tap spacing).
    Returns dict with every intermediate signal needed for plotting/analysis.
    """
    _, h = rrc_filter(beta, span, sps)
    L = span * sps + 1              # RRC filter length (odd, symmetric -> linear phase)
    delay_samples = (L - 1) // 2    # single-filter group delay, in samples

    symbols, bits = bpsk_symbols(n_sym, rng)
    tx_up = upsample(symbols, sps)
    tx_shaped = np.convolve(tx_up, h)  # transmit (pulse-shaped) signal

    ch_out = tx_shaped
    if channel_taps is not None:
        # multipath: taps spaced one symbol period apart
        ch_ir = np.zeros((len(channel_taps) - 1) * sps + 1)
        ch_ir[::sps] = channel_taps
        ch_out = np.convolve(tx_shaped, ch_ir)

    rx_noisy = add_awgn(ch_out, snr_db, sps)
    rx_matched = np.convolve(rx_noisy, h)  # matched-filter output

    # Two convolutions with the (symmetric, linear-phase) RRC filter -> total
    # cascade delay is the sum of the two individual filter group delays.
    # A symbol-spaced multipath channel (taps at k*sps) adds no *extra*
    # sub-symbol shift for tap 0, so the same total_delay is used to locate
    # the main (first) received ray.
    total_delay = 2 * delay_samples

    return {
        "symbols": symbols, "bits": bits, "h": h, "sps": sps, "span": span,
        "tx_shaped": tx_shaped, "rx_matched": rx_matched,
        "delay_samples": delay_samples, "total_delay": total_delay,
    }


def decide_symbols(rx_matched, sps, total_delay, n_sym, timing_offset_frac=0.0):
    """
    Slice the matched-filter output at the correct (delay-compensated) instants.
    timing_offset_frac: fractional-symbol sampling offset (e.g. 0.25 = quarter symbol early/late)
    """
    offset_samples = int(round(timing_offset_frac * sps))
    start = total_delay + offset_samples
    idx = start + np.arange(n_sym) * sps
    idx = idx[(idx >= 0) & (idx < len(rx_matched))]
    samples = rx_matched[idx]
    decided = np.sign(samples)
    decided[decided == 0] = 1
    return samples, decided, idx


# ----------------------------------------------------------------------
# 3. Reusable eye-diagram function (no toolbox)
# ----------------------------------------------------------------------
def eye_diagram(ax, signal, sps, start, n_traces=200, n_symbol_periods=2,
                 color="C0", alpha=0.25, title=""):
    """
    Plot a (n_symbol_periods)-symbol-wide eye diagram of `signal`
    starting at sample `start` (i.e. after the cascade delay has been
    removed, so traces are correctly centred).
    """
    win = n_symbol_periods * sps
    n_avail = (len(signal) - start) // sps
    n_traces = min(n_traces, n_avail - n_symbol_periods)
    t_axis = np.arange(win) / sps  # in symbol periods

    for k in range(n_traces):
        seg = signal[start + k * sps: start + k * sps + win]
        if len(seg) < win:
            break
        ax.plot(t_axis, seg, color=color, alpha=alpha, linewidth=0.8)

    ax.set_xlabel("Time (symbol periods)")
    ax.set_ylabel("Amplitude")
    ax.set_title(title)
    ax.axvline(n_symbol_periods / 2, color="k", linewidth=0.7, linestyle="--")
    ax.grid(alpha=0.3)
    return t_axis


def eye_height(signal, sps, start, n_traces=500):
    """
    Estimate eye height at the optimum sampling instant: the gap between the
    minimum of the 'high' traces and the maximum of the 'low' traces, at the
    centre of the eye.
    """
    n_avail = (len(signal) - start) // sps
    n_traces = min(n_traces, n_avail - 1)
    centre_samples = signal[start: start + n_traces * sps: sps]
    pos = centre_samples[centre_samples > 0]
    neg = centre_samples[centre_samples <= 0]
    if len(pos) == 0 or len(neg) == 0:
        return 0.0
    return pos.min() - neg.max()


def theoretical_ber_bpsk(snr_db):
    """Theoretical BER of BPSK over AWGN with a matched-filter (correlation)
    receiver: Pe = Q(sqrt(2*Es/N0)) = 0.5*erfc(sqrt(Es/N0))."""
    snr_lin = 10 ** (np.asarray(snr_db) / 10)
    return 0.5 * erfc(np.sqrt(snr_lin))


# ----------------------------------------------------------------------
# 4. Main: build every figure required by the lab sheet
# ----------------------------------------------------------------------
if __name__ == "__main__":
    SPS, SPAN, BETA = 8, 6, 0.35
    N_SYM = 4000

    # ---- Task 28-29: Tx / matched-filter output, delay validation -----
    res = matched_filter_chain(n_sym=N_SYM, sps=SPS, span=SPAN, beta=BETA, snr_db=12)
    samples, decided, idx = decide_symbols(res["rx_matched"], SPS, res["total_delay"], N_SYM)
    ber_check = np.mean(decided != np.where(res["bits"][:len(decided)] == 1, 1, -1))
    print(f"[Validation] RRC length = {SPAN*SPS+1} samples, "
          f"single-filter group delay = {res['delay_samples']} samples "
          f"= {res['delay_samples']/SPS:.2f} symbol periods, "
          f"total cascade (tx+rx) delay = {res['total_delay']} samples "
          f"= {res['total_delay']/SPS:.2f} symbol periods.")
    print(f"[Validation] First decided symbol index in rx_matched = {idx[0]} "
          f"(>= total_delay = {res['total_delay']}: {idx[0] >= res['total_delay']}) -> "
          f"decisions are taken only AFTER delay removal.")
    print(f"[Validation] Sanity BER at 12 dB, zero timing offset = {ber_check:.4f}")

    fig, ax = plt.subplots(2, 1, figsize=(9, 6), sharex=True)
    n_show = 40 * SPS
    ax[0].plot(res["tx_shaped"][:n_show])
    ax[0].set_title("Transmit signal after RRC pulse shaping")
    ax[0].set_ylabel("Amplitude")
    ax[0].grid(alpha=0.3)

    ax[1].plot(res["rx_matched"][:n_show + res["total_delay"]])
    ax[1].axvline(res["total_delay"], color="r", linestyle="--",
                   label=f"Cascade delay = {res['total_delay']} samples")
    mark_idx = idx[idx < n_show + res["total_delay"]]
    ax[1].plot(mark_idx, res["rx_matched"][mark_idx], "ko", markersize=4,
               label="Decision instants (post delay-removal)")
    ax[1].set_title("Matched-filter output (delay compensated)")
    ax[1].set_xlabel("Sample index")
    ax[1].set_ylabel("Amplitude")
    ax[1].legend(loc="upper right", fontsize=8)
    ax[1].grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig("figs/fig1_tx_rx_waveform.png", dpi=150)
    plt.show()

    # ---- Task 30a: Eye diagrams for several SNRs ------------------------
    snr_list = [20, 10, 5, 0]
    fig, axes = plt.subplots(2, 2, figsize=(9, 7))
    for ax, snr in zip(axes.flat, snr_list):
        r = matched_filter_chain(n_sym=N_SYM, sps=SPS, span=SPAN, beta=BETA, snr_db=snr)
        eye_diagram(ax, r["rx_matched"], SPS, r["total_delay"],
                    n_traces=250, color="C0", title=f"SNR = {snr} dB")
    fig.suptitle("Eye diagrams vs SNR (beta = 0.35)")
    fig.tight_layout()
    fig.savefig("figs/fig2_eye_vs_snr.png", dpi=150)
    plt.show()

    # ---- Task 30b: Eye diagrams for several timing offsets --------------
    r = matched_filter_chain(n_sym=N_SYM, sps=SPS, span=SPAN, beta=BETA, snr_db=12)
    offsets = [0.0, 0.15, 0.30, 0.5]
    fig, axes = plt.subplots(2, 2, figsize=(9, 7))
    for ax, off in zip(axes.flat, offsets):
        start = r["total_delay"] + int(round(off * SPS))
        eye_diagram(ax, r["rx_matched"], SPS, start, n_traces=250,
                    color="C1", title=f"Timing offset = {off:.2f} T")
    fig.suptitle("Eye diagrams vs sampling offset (SNR = 12 dB)")
    fig.tight_layout()
    fig.savefig("figs/fig3_eye_vs_offset.png", dpi=150)
    plt.show()

    # ---- Task 30c: Eye height vs SNR -------------------------------------
    snr_range = np.arange(-2, 21, 2)
    heights = []
    for snr in snr_range:
        r = matched_filter_chain(n_sym=3000, sps=SPS, span=SPAN, beta=BETA, snr_db=snr)
        heights.append(eye_height(r["rx_matched"], SPS, r["total_delay"]))
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(snr_range, heights, "o-", color="C2")
    ax.set_xlabel("SNR (dB)")
    ax.set_ylabel("Eye height (linear amplitude)")
    ax.set_title("Eye height vs SNR")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig("figs/fig4_eyeheight_vs_snr.png", dpi=150)
    plt.show()

    # ---- Task 30d + 31: BER vs timing offset, with & without ISI --------
    offset_range = np.linspace(-0.5, 0.5, 21)
    ber_no_isi, ber_isi = [], []
    isi_taps = [1.0, 0.5, -0.25]  # 3-tap multipath channel -> ISI
    N_BER = 20000
    for off in offset_range:
        r1 = matched_filter_chain(n_sym=N_BER, sps=SPS, span=SPAN, beta=BETA, snr_db=10)
        _, dec1, _ = decide_symbols(r1["rx_matched"], SPS, r1["total_delay"], N_BER, off)
        ref1 = np.where(r1["bits"][:len(dec1)] == 1, 1, -1)
        ber_no_isi.append(np.mean(dec1 != ref1))

        r2 = matched_filter_chain(n_sym=N_BER, sps=SPS, span=SPAN, beta=BETA, snr_db=10,
                                   channel_taps=isi_taps)
        _, dec2, _ = decide_symbols(r2["rx_matched"], SPS, r2["total_delay"], N_BER, off)
        ref2 = np.where(r2["bits"][:len(dec2)] == 1, 1, -1)
        ber_isi.append(np.mean(dec2 != ref2))

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.semilogy(offset_range, np.array(ber_no_isi) + 1e-5, "o-", label="No multipath (AWGN only)")
    ax.semilogy(offset_range, np.array(ber_isi) + 1e-5, "s-", label="Multipath ISI channel")
    ax.set_xlabel("Timing offset (symbol periods)")
    ax.set_ylabel("BER")
    ax.set_title("BER vs sampling-timing offset (SNR = 10 dB)")
    ax.legend()
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig("figs/fig5_ber_vs_offset.png", dpi=150)
    plt.show()

    # ---- Task 31: multipath ISI eye diagram (closed eye) ----------------
    r_isi = matched_filter_chain(n_sym=N_SYM, sps=SPS, span=SPAN, beta=BETA, snr_db=15,
                                  channel_taps=isi_taps)
    r_clean = matched_filter_chain(n_sym=N_SYM, sps=SPS, span=SPAN, beta=BETA, snr_db=15)
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5))
    eye_diagram(axes[0], r_clean["rx_matched"], SPS, r_clean["total_delay"],
                n_traces=250, color="C0", title="No multipath (ISI-free)")
    eye_diagram(axes[1], r_isi["rx_matched"], SPS, r_isi["total_delay"],
                n_traces=250, color="C3", title="With multipath channel [1, 0.5, -0.25]")
    fig.suptitle("Effect of multipath ISI on the eye diagram (SNR = 15 dB)")
    fig.tight_layout()
    fig.savefig("figs/fig6_isi_eye.png", dpi=150)
    plt.show()

    print("All figures saved to figs/")

    # ---- Extra: simulated BER vs SNR against the theoretical BPSK bound --
    snr_range_ber = np.arange(0, 13, 2)
    ber_sim = []
    for snr in snr_range_ber:
        r = matched_filter_chain(n_sym=40000, sps=SPS, span=SPAN, beta=BETA, snr_db=snr)
        _, dec, _ = decide_symbols(r["rx_matched"], SPS, r["total_delay"], 40000, 0.0)
        ref = np.where(r["bits"][:len(dec)] == 1, 1, -1)
        ber_sim.append(np.mean(dec != ref))
    ber_theory = theoretical_ber_bpsk(snr_range_ber)

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.semilogy(snr_range_ber, ber_theory, "k-", linewidth=2, label=r"Theory: $Q(\sqrt{2E_s/N_0})$")
    ax.semilogy(snr_range_ber, np.array(ber_sim) + 1e-6, "o", color="C3",
                markersize=7, label="Simulated (matched filter, zero offset)")
    ax.set_xlabel("SNR = $E_s/N_0$ (dB)")
    ax.set_ylabel("BER")
    ax.set_title("Simulated vs theoretical BPSK BER (matched-filter receiver)")
    ax.legend()
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig("figs/fig7_ber_vs_snr_theory.png", dpi=150)
    plt.show()

    print("SNR(dB)  BER_sim     BER_theory")
    for snr, bs, bt in zip(snr_range_ber, ber_sim, ber_theory):
        print(f"{snr:5.0f}   {bs:.6f}   {bt:.6e}")